version: '3.8'

services:
  backend:
    build: ./App
    container_name: claim_backend
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./App/frontend
    container_name: claim_frontend
    ports:
      - "5001:5000"
    depends_on:
      - backend